[project]
name = "proiect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Popescu", email = "andrei69420@yahoo.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "streamlit>=1.61.1",
    "supabase>=2.31.0",
]

[project.scripts]
proiect = "proiect:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
