-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

CREATE TABLE public.workflow_runs (
  run_id             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  request_id         character varying        NOT NULL,
  suggested_licenses jsonb                    DEFAULT '[]'::jsonb NOT NULL,
  suggested_hardware jsonb                    DEFAULT '{}'::jsonb NOT NULL,
  policy_citations   jsonb                    DEFAULT '[]'::jsonb NOT NULL,
  it_notes           text,
  reviewed_by        character varying,
  created_at         timestamp with time zone DEFAULT now() NOT NULL,
  updated_at         timestamp with time zone DEFAULT now()
);

ALTER TABLE public.workflow_runs
  ADD CONSTRAINT workflow_runs_pkey PRIMARY KEY (run_id);

ALTER TABLE public.workflow_runs
  ADD CONSTRAINT workflow_runs_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.onboarding_requests(request_id) ON DELETE CASCADE;

GRANT ALL ON public.workflow_runs TO anon;

GRANT ALL ON public.workflow_runs TO authenticated;

GRANT ALL ON public.workflow_runs TO service_role;